- name: install various tools
  tags: i3
  become: true
  ansible.builtin.apt:
    pkg:
      - i3                      # window-manager
      - playerctl               # play-pause, previous, next commands
      - feh                     # wallpaper
      - arandr                  # gui tool for xrandr (multi-monitor)
      - fonts-font-awesome

# currently from: https://imgur.com/a/2JEMhoy
- name: wallpaper
  tags: wallpaper
  ansible.builtin.copy:
    src: files/wallpaper.png
    dest: ~/.Pictures/wallpaper.png
    mode: '0600'

## todo: make this run if the wallpaper changes:
# https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background
# wget -qO - https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/archive/main.tar.gz
#    | tar zx --strip-components=1 ubuntu-gdm-set-background-main/ubuntu-gdm-set-background
# sudo ./ubuntu-gdm-set-background --image ~/Pictures/wallpaper.png

- name: config
  tags: i3
  ansible.builtin.copy:
    src: files/{{inventory_hostname}}
    dest: ~/.config/i3/config
    mode: '0600'

- name: Make sure the ~/.fonts directory exists
  tags: fonts
  ansible.builtin.file:
    path: ~/.fonts
    state: directory
    mode: '0755'

- name: Install font-awesome fonts
  tags: fonts
  ansible.builtin.unarchive:
    src: https://use.fontawesome.com/releases/v6.2.0/fontawesome-free-6.2.0-desktop.zip
    remote_src: true
    dest: ~/.fonts/
    include:
    - '*.otf'
