- name: install android / java tools
  become: true
  ansible.builtin.apt:
    pkg:
      - openjdk-11-jdk
      - adb
      - android-sdk-platform-tools-common

- name: adding {{ username }} to group plugdev for adb
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: plugdev
    append: true
