---
# tasks for installing lapce on Ubuntu 22.04
- name: Download and install lapce binary
  become: true
  tags: lapce
  ansible.builtin.unarchive:
    src: https://github.com/lapce/lapce/releases/latest/download/lapce-linux-amd64.tar.gz
    remote_src: true
    extra_opts: ['--strip-components=1', '--show-stored-names']
    dest: /usr/bin

- name: Get logo for lapce launcher icon
  become: true
  tags: lapce
  ansible.builtin.get_url:
    url: https://github.com/lapce/lapce/blob/master/extra/images/logo.png?raw=true
    dest: /usr/share/pixmaps/dev.lapce.lapce.png
    mode: '644'
    checksum: md5:dca7d444edece3006ec30dd96785ad8f

- name: Get desktop file for lapce launcher
  become: true
  tags: lapce
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/lapce/lapce/refs/heads/master/extra/linux/dev.lapce.lapce.desktop
    dest: /usr/share/applications/dev.lapce.lapce.desktop
    mode: '644'
    checksum: md5:1d2a1aea7a895ab2732586a0994c919f

- name: Get metainfo file for lapce launcher
  become: true
  tags: lapce
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/lapce/lapce/refs/heads/master/extra/linux/dev.lapce.lapce.metainfo.xml
    dest: /usr/share/metainfo/dev.lapce.lapce.metainfo.xml
    mode: '644'
    checksum: md5:941c04f3e244cab798eb634e1c0e38d7
