---
- name: Install vscode apt repo
  tags: vscode
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: https://packages.microsoft.com/repos/code
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    suites: [stable]
    components: [main]
    state: present
    enabled: yes

- name: Install vscode
  become: true
  tags: vscode
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - code

- name: Install jetbrains toolbox
  tags: jetbrains
  ansible.builtin.include_role:
    name: webarchitect609.jet_brains_toolbox
    apply:
      become: true