---
# Watchtower configuration
common_cli_watchtower_enabled: true
common_cli_watchtower_schedule: "0 0 4 * * *" # Daily at 4 AM (cron format: second minute hour day month dayOfWeek)
common_cli_watchtower_cleanup: true
common_cli_watchtower_include_stopped: false
common_cli_watchtower_debug: false
common_cli_watchtower_timezone: "America/Los_Angeles"
common_cli_watchtower_monitor_only: false
common_cli_watchtower_notification_url: ""
