---
- name: Install android tools
  tags: android
  become: true
  ansible.builtin.apt:
    pkg:
      - adb
      - android-sdk-platform-tools-common

- name: Add {{ username }} to group plugdev for adb
  become: true
  tags: android
  ansible.builtin.user:
    name: "{{ username }}"
    groups: plugdev
    append: true

- name: Install java tools
  tags: java
  become: true
  ansible.builtin.apt:
    pkg:
      - openjdk-21-jdk

- name: Install cpp development tools
  become: true
  tags: cpp
  ansible.builtin.apt:
    pkg:
      - build-essential
      - cmake
      - autoconf
      - strace
      - ltrace
      - valgrind
      - hotspot
      - heaptrack
      - clang-format
      - clang-tidy
      - pkg-config

- name: Install ubuntu-specific development tools (perf)
  become: true
  ansible.builtin.apt:
    pkg:
      - linux-tools-common
      - linux-tools-generic
  when: ansible_distribution == 'Ubuntu'

- name: Install debian-specific development tools (perf)
  become: true
  ansible.builtin.apt:
    pkg:
      - linux-perf
  when: ansible_distribution == 'Debian'

- name: Install golang tools
  tags: golang
  become: true
  ansible.builtin.apt:
    pkg:
      - golang

- name: Install node development tools
  become: true
  tags: 
    - node
    - npm
  ansible.builtin.apt:
    pkg:
      - npm

# yarn: https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/how-to-install-yarn-on-ubuntu-22-04-ubuntu-20-04.html
# https://docs.ansible.com/ansible/latest/collections/community/general/npm_module.html
- name: Install yarn node.js package
  become: true
  tags: 
    - yarn
    - node
    - npm
  community.general.npm:
    name: yarn
    global: true

- name: Install tldr node package # https://tldr.sh/
  become: true
  tags: 
    - tldr
    - node
    - npm
  community.general.npm:
    name: tldr
    global: true

- name: Add php ppa repository
  become: true
  tags: php
  ansible.builtin.deb822_repository:
    name: php-ppa
    state: present
    types: [deb]
    uris: "https://ppa.launchpadcontent.net/ondrej/php/ubuntu"
    suites: ["{{ ansible_distribution_release|lower }}"]
    components: [main]
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xB8DC7E53946656EFBCE4C1DD71DAEAAB4AD4CAB6"
    enabled: yes

- name: Install php and php dev tools
  tags: php
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.php

- name: Install python development tools
  become: true
  tags: python
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-setuptools
      - python-is-python3
      - python3-poetry

- name: Install rust development tools
  tags: rust
  become: true
  ansible.builtin.apt:
    pkg:
      - rustc

- name: Install ruby development tools
  tags: ruby
  become: true
  ansible.builtin.apt:
    pkg:
      - ruby-full

- name: Create zig directory if it does not exist
  tags: zig
  become: true
  ansible.builtin.file:
    path: /opt/zig
    state: directory
    mode: '0755'

- name: Install zig development tools
  tags: zig
  become: true
  ansible.builtin.unarchive:
    src: https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
    dest: /opt/zig
    extra_opts: ['--strip-components=1', '--show-stored-names']
    remote_src: true

- name: Symlink zig program to /usr/local/bin
  tags: zig
  become: true
  ansible.builtin.file:
    src: /opt/zig/zig
    dest: /usr/local/bin/zig
    state: link

- name: Install dotcl (digital ocean ctl)
  become: true
  tags: doctl
  ansible.builtin.unarchive:
    src: >
      https://github.com/digitalocean/doctl/releases/download/v1.119.1/doctl-1.119.1-linux-{{ [ansible_architecture] | map('extract', deb_architecture) | first }}.tar.gz
    dest: /usr/local/bin
    remote_src: true

# note: this will require a restart to apply changes
- name: Set digitalocean access token
  become: true
  tags: doctl
  ansible.builtin.copy:
    content: "DIGITALOCEAN_ACCESS_TOKEN={{ lookup('community.general.onepassword', 'DigitalOcean', field='credential', vault='Infrastructure') }}"
    dest: /etc/environment.d/90-digitalocean.conf

- name: Add hashicorp repository
  become: true
  tags: hashicorp
  ansible.builtin.deb822_repository:
    name: hashicorp
    state: present
    types: [deb]
    uris: "https://apt.releases.hashicorp.com"
    suites: "{{ ansible_distribution_release }}"
    components: [main]
    signed_by: "https://apt.releases.hashicorp.com/gpg"
    enabled: yes

- name: Install hashicorp tools
  become: true
  tags:
    - hashicorp
    - vagrant
    - terraform
    - packer
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - vagrant
      - terraform
      - packer