# golang
- name: add go GPG
  tags: go
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 52B59B1571A79DBC054901C0F6BC817356A3D45E
    keyring: /etc/apt/trusted.gpg.d/golang.gpg

- name: add go repository
  tags: go
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:longsleep/golang-backports

# - name: update apt and install go
#   tags: go
#   become: true
#   ansible.builtin.apt:
#     update_cache: true
#     name: golang-go
#     state: present

- name: Update bashrc go
  tags: go
  ansible.builtin.lineinfile:
    dest: "/home/{{ username }}/.bashrc"
    owner: "{{ username }}"
    line: "{{ item }}"
  with_items:
    - "export GOPATH=$HOME/go"
    - "export PATH=$PATH:$GOROOT/bin:$GOPATH/bin"
