- name: Create Rust Monthly Directories
  tags: rust-game
  become: true
  ansible.builtin.file:
    path: /etc/rust-monthly
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Create Rust Weekly Directories
  tags: rust-game
  become: true
  ansible.builtin.file:
    path: /etc/rust-weekly
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Copy Rust Monthly config to host
  tags: rust-game
  become: true
  ansible.builtin.template:
    src: files/rust.env.j2
    dest: /etc/rust-monthly/rust.env
    mode: '644'
    owner: root
    group: root
  vars:
    rust_identity: rust_docker
    rust_seed: 30
    rust_server_name: "California | Monthly | No BP Wipe"
    rust_server_description: "Self hosted in Redwood City CA"
    rust_world_size: 4500
    rust_server_port: 28015
    rust_server_query_port: 28016
    rust_rcon_port: 28017
    rust_app_port: 28082
    rust_oxide_enabled: 1
    rust_server_url: https://discord.gg/4Dc3FUVD
    rust_banner_url: https://gcdnb.pbrd.co/images/TC7pjSZx3Zd6.jpg

- name: Copy Rust Weekly config to host
  tags: rust-game
  become: true
  ansible.builtin.template:
    src: files/rust.env.j2
    dest: /etc/rust-weekly/rust.env
    mode: '644'
    owner: root
    group: root
  vars:
    rust_identity: rust_docker_weekly
    rust_seed: 17
    rust_server_name: "California | Weekly | No BP Wipe"
    rust_server_description: "Self hosted in Redwood City CA"
    rust_world_size: 4000
    rust_server_port: 27015
    rust_server_query_port: 27016
    rust_rcon_port: 27017
    rust_app_port: 27082
    rust_oxide_enabled: 0
    rust_server_url: https://discord.gg/4Dc3FUVD
    rust_banner_url: https://gcdnb.pbrd.co/images/TC7pjSZx3Zd6.jpg

- name: Deploy Rust Monthly
  tags: rust-game
  # vars:
  #   ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: rust
    image: didstopia/rust-server
    pull: true
    volumes:
      - "/etc/rust-monthly:/steamcmd/rust:rw"
    env_file: /etc/rust-monthly/rust.env
    ports:
      - "28015:28015"
      - "28015:28015/udp"
      - "28016:28016"
      - "28016:28016/udp"
      - "28017:28017"
      - "28017:28017/udp"
      - "8000:8080"
      - "28082:28082"
      - "28082:28082/udp"
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: 10g

- name: Deploy Rust Weekly
  tags: rust-game
  # vars:
  #   ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: rust-weekly
    image: didstopia/rust-server
    pull: true
    volumes:
      - "/etc/rust-weekly:/steamcmd/rust:rw"
    env_file: /etc/rust-weekly/rust.env
    ports:
      - "27015:27015"
      - "27015:27015/udp"
      - "27016:27016"
      - "27016:27016/udp"
      - "27017:27017"
      - "27017:27017/udp"
      - "8001:8080"
      - "27082:27082"
      - "27082:27082/udp"
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: 10g
