- name: Create Rust Monthly Directories
  tags: rust-game
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '755'
    owner: root
    group: root
  loop:
    - /etc/rust-monthly
    - /etc/rust-monthly/oxide
    - /etc/rust-monthly/oxide/plugins
    - /etc/rust-monthly/cfg

- name: Create Rust Weekly Directories
  tags: rust-game
  become: true
  ansible.builtin.file:
    path: "{{ item}}"
    state: directory
    mode: '755'
    owner: root
    group: root
  loop:
    - /etc/rust-weekly
    - /etc/rust-weekly/oxide
    - /etc/rust-weekly/oxide/plugins
    - /etc/rust-weekly/cfg

- name: Copy oxide plugins to Monthly
  tags: rust-game
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '644'
    owner: root
    group: root
  loop:
    - src: files/oxide.config.json
      dest: /etc/rust-monthly/oxide/oxide.config.json
    - src: files/RustadminOnline.cs
      dest: /etc/rust-monthly/oxide/plugins/RustadminOnline.cs

- name: Copy oxide plugins to Weekly
  tags: rust-game
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '644'
    owner: root
    group: root
  loop:
    - src: files/oxide.config.json
      dest: /etc/rust-weekly/oxide/oxide.config.json
    - src: files/RustadminOnline.cs
      dest: /etc/rust-weekly/oxide/plugins/RustadminOnline.cs

- name: Copy Rust Monthly config to host
  tags: rust-game
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '644'
    owner: root
    group: root
  loop:
    - src: files/rust.env.j2
      dest: /etc/rust-monthly/rust.env
    - src: files/server.cfg.j2
      dest: /etc/rust-monthly/server/rust_docker/cfg/server.cfg
  vars:
    rust_server_tags: vanilla,monthly,NA
    rust_cron_wipe_schedule: 0 19 4 * *
    rust_startup_args: -load -nographics +server.secure 1 +server.tags {{ rust_server_tags }} +wipeTimezone America/Los_Angeles
    rust_identity: rust_docker
    rust_seed: "{{ 2147483647 | random }}"
    rust_server_name: "California | Monthly | No BP Wipe"
    rust_server_description: "Self hosted in Redwood City CA"
    rust_world_size: 4500
    rust_server_port: 28015
    rust_server_query_port: 28016
    rust_rcon_port: 28017
    rust_app_port: 28082
    rust_oxide_enabled: 1
    rust_server_url: https://discord.gg/t77M3yAgKu
    rust_banner_url: https://images2.imgbox.com/37/6d/fOpdrpYS_o.jpeg

- name: Copy Rust Weekly config to host
  tags: rust-game
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '644'
    owner: root
    group: root
  loop:
    - src: files/rust.env.j2
      dest: /etc/rust-weekly/rust.env
    - src: files/server.cfg.j2
      dest: /etc/rust-weekly/server/rust_docker_weekly/cfg/server.cfg
  vars:
    rust_server_tags: vanilla,weekly,NA
    rust_cron_wipe_schedule: 0 19 * * 4
    rust_startup_args: -load -nographics +server.secure 1 +server.tags {{ rust_server_tags }} +wipeTimezone America/Los_Angeles
    rust_identity: rust_docker_weekly
    rust_seed: "{{ 2147483647 | random }}"
    rust_server_name: "California | Weekly | No BP Wipe"
    rust_server_description: "Self hosted in Redwood City CA"
    rust_world_size: 3000
    rust_server_port: 27015
    rust_server_query_port: 27016
    rust_rcon_port: 27017
    rust_app_port: 27082
    rust_oxide_enabled: 1
    rust_server_url: https://discord.gg/t77M3yAgKu
    rust_banner_url: https://images2.imgbox.com/37/6d/fOpdrpYS_o.jpeg

- name: Deploy Rust Monthly
  tags: rust-game
  # vars:
  #   ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: rust
    image: ghcr.io/compscidr/rust-server
    pull: true
    volumes:
      - "/etc/rust-monthly:/steamcmd/rust:rw"
    env_file: /etc/rust-monthly/rust.env
    ports:
      - "28015:28015"
      - "28015:28015/udp"
      - "28016:28016"
      - "28016:28016/udp"
      - "28017:28017"
      - "28017:28017/udp"
      - "8000:8080"
      - "28082:28082"
      - "28082:28082/udp"
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: 16g

- name: Deploy Rust Weekly
  tags: rust-game
  # vars:
  #   ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: rust-weekly
    image: ghcr.io/compscidr/rust-server
    pull: true
    volumes:
      - "/etc/rust-weekly:/steamcmd/rust:rw"
    env_file: /etc/rust-weekly/rust.env
    ports:
      - "27015:27015"
      - "27015:27015/udp"
      - "27016:27016"
      - "27016:27016/udp"
      - "27017:27017"
      - "27017:27017/udp"
      - "8001:8080"
      - "27082:27082"
      - "27082:27082/udp"
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: 16g
