---
- name: Install Sudo
  tags: user
  become: true
  ansible.builtin.apt:
    pkg:
      - sudo
      - ssh-import-id

- name: Ensure group "pcap" exists
  tags: user
  become: true
  ansible.builtin.group:
    name: pcap
    state: present

- name: Add the user 'jason'
  tags: user
  become: true
  ansible.builtin.user:
    name: "jason"
    password: "{{ vault_password|password_hash('sha512') }}"
    comment: "Jason Ernst"
    shell: /bin/bash
    append: true
    groups: sudo,pcap
    skeleton: "/etc/skel"
    create_home: true
    update_password: always

- name: Create ssh directory if it does not exist
  tags: user
  become: true
  ansible.builtin.file:
    path: /home/jason/.ssh
    state: directory
    mode: '0700'
    owner: jason
    group: jason

- name: Import SSH authorized key
  tags: user
  become: true
  ansible.builtin.copy:
    src: files/ssh/authorized_keys
    dest: /home/jason/.ssh/authorized_keys
    mode: '0600'
    owner: jason
    group: jason

# pgp keys see: https://github.com/netson/ansible-gpg-key
# and https://github.com/cpmills1975/ansible-gpg-import-module
# and https://github.com/brandonkal/ansible-gpg
- name: Create gpg directory if it does not exist
  tags: gpg
  become_user: jason
  ansible.builtin.file:
    path: ~/.gpg
    state: directory
    mode: '0700'
    owner: jason
    group: jason

- name: Copy Public GPG Key
  become_user: jason
  tags: gpg
  ansible.builtin.copy:
    src: files/gpg/mygpgkey_pub.gpg
    dest: ~/.gpg/mygpgkey_pub.gpg
    mode: '0600'
    owner: jason
    group: jason
  notify:
    - Import Public GPG Key

- name: Copy Private GPG Key
  tags: gpg
  become_user: jason
  ansible.builtin.copy:
    src: files/gpg/mygpgkey_sec.gpg
    dest: ~/.gpg/mygpgkey_sec.gpg
    mode: '0600'
    owner: jason
    group: jason
  notify:
    - Import Private PGP Key

# todo: figure out how to make this not reproduced
- name: Run whoami without become.
  tags: bash_alias
  command: whoami
  changed_when: false
  become: false
  register: whoami

- name: Set a fact with the user name.
  tags: bash_alias
  set_fact:
    login_user: "{{ whoami.stdout }}"

- name: Ensure bash aliases file exists
  tags: bash_alias
  ansible.builtin.file:
    path: "/home/{{ login_user }}/.bash_aliases"
    state: touch
    mode: 0600
    owner: "{{ login_user }}"
    group: "{{ login_user }}"


- name: Create ~/.config/autostart directory if it does not exist
  tags: config/autostart
  become_user: jason
  ansible.builtin.file:
    path: ~/.config/autostart
    state: directory
    mode: '0700'
    owner: jason
    group: jason
