---
- name: Import GPG private key
  tags: gpg
  become_user: "{{ username }}"
  gpg:
    key_file: "~/.gpg/{{ username }}.gpg"
    key_id: "{{ signingkey }}"
    key_type: private

# used when we make a change to the user like them
# to a group
- name: Reset ssh connection
  ansible.builtin.meta:
    reset_connection

- name: Build directories list
  tags: dotfiles
  find:
    paths: [~/dotfiles/]
    recurse: no
    file_type: directory
  register: files
  notify: Deploy dotfiles 
 
- name: Deploy dotfiles
  become_user: "{{ username }}"
  tags: dotfiles
  with_items: "{{ files.files }}"
  shell: "stow {{ item.path | basename }}"
  args:
    chdir: ~/dotfiles
