# runs transmission behind nordvpn
- name: Deploy Transmission
  tags: transmission
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: transmission
    image: haugene/transmission-openvpn:4.3
    pull: true
    volumes: /storage/downloads:/data
    devices:
      - /dev/net/tun
    capabilities:
      - NET_ADMIN
    env:
      TRANSMISSION_WEB_UI: "transmission-web-control"
      PUID: "1000"
      PGID: "1000"
      OPENVPN_PROVIDER: NORDVPN
      NORDVPN_PROTOCOL: udp
      OPENVPN_USERNAME: "{{ nordvpn_user }}"
      OPENVPN_PASSWORD: "{{ nordvpn_password }}"
      NORDVPN_COUNTRY: US
      NORDVPN_CATEGORY: legacy_p2p
      LOCAL_NETWORK: 10.0.0.0/24
      HEALTH_CHECK_HOST: 8.8.8.8
      OPENVPN_OPTS: ""
      TZ: America/Los_Angeles
    restart_policy: unless-stopped
    published_ports: 9091:9091
    ports:
      - "9091:9091"
