---
- name: Restart device source
  become: true
  ansible.builtin.systemd:
    name: sair-device-source
    state: restarted

- name: Restart proxy
  become: true
  ansible.builtin.systemd:
    name: sair-proxy
    state: restarted
