# https://waylonwalker.com/til/install-rust/
- name: check if cargo is installed
  tags: rust
  ansible.builtin.command: command -v cargo
  register: cargo_exists
  ignore_errors: true
  changed_when: false

- name: Download Installer
  tags: rust
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: true

- name: install rust/cargo
  tags: rust
  when: cargo_exists is failed
  ansible.builtin.command: /tmp/sh.rustup.rs -y
