---
- name: Include common playbook
  ansible.builtin.import_playbook: ../../common.yml
  
# Including dev playbook only if needed
- name: Include dev playbook
  ansible.builtin.import_playbook: ../../dev.yml
