---
- name: Test local roles
  hosts: all
  tasks:
    - name: Verify environment
      ansible.builtin.debug:
        msg: "Running molecule test on {{ ansible_distribution }} {{ ansible_distribution_version }}"
      
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      become: true
      
    - name: Install test package
      ansible.builtin.apt:
        name: curl
        state: present
      become: true
