---
# Create symbolic links to vars files
- name: Setup for playbook execution
  hosts: all
  gather_facts: true
  tasks:
    # Create the vars directory structure
    - name: Create vars directory
      file:
        path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/vars"
        state: directory
        mode: '0755'
      delegate_to: localhost

    # Create mock vars files in the vars directory
    - name: Create mock vars files
      copy:
        dest: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/vars/{{ item.filename }}"
        content: "{{ item.content }}"
      loop:
        - filename: "user.yml"
          content: |
            username: ansible
            fullname: Test User
            email: test@example.com
            signingkey: testkeyabc123
        - filename: "deb_arch.yml"
          content: |
            # Architecture mapping
            deb_architecture: {
                "armv6l": "armhf",
                "armv7l": "armhf",
                "aarch64": "arm64", 
                "x86_64": "amd64",
                "i386": "i386"
            }
      delegate_to: localhost

# Import the real playbooks
- import_playbook: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/common.yml"
- import_playbook: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/dev.yml"
