---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example verification task
      ansible.builtin.command: echo "Verification successful"
      register: test_output
      changed_when: false

    - name: Display test output
      ansible.builtin.debug:
        var: test_output.stdout