---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if packages are installed
      command: rpm -q {{ item }}
      register: pkg_check
      changed_when: false
      loop:
        - curl
        - git
        - htop
        - gcc
        - python3-pip
      ignore_errors: true
      
    - name: Report package installation status
      debug:
        msg: "Package {{ item.item }} {{ 'is' if item.rc == 0 else 'is not' }} installed"
      loop: "{{ pkg_check.results }}"
    
    - name: Verify common.yml and dev.yml packages were installed
      assert:
        that:
          - pkg_check.results | selectattr('rc', 'eq', 0) | list | length > 3
        fail_msg: "Required packages from common.yml and dev.yml were not installed"
        success_msg: "Packages from common.yml and dev.yml were successfully installed"
