- name: Deploy DynDns
  tags: dyndns
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: dyndns
    image: tunix/digitalocean-dyndns
    pull: true
    env:
      DIGITALOCEAN_TOKEN: "{{ lookup('ansible.builtin.env', 'DIGITALOCEAN_TOKEN') }}"
      DOMAIN: "jasonernst.com"
      NAME: "home"
      SLEEP_INTERVAL: "60"
      REMOVE_DUPLICATES: "true"
    restart_policy: unless-stopped
    memory: 1g