- name: Update the ssh/config with each of the lan node name entries
  tags: ssh
  ansible.builtin.blockinfile:
    create: true
    mode: '0600'
    path: "/home/{{ username }}/.ssh/config"
    block: |
      Host {{ item }}
      Hostname {{ item }}
      User {{ username }}
      IdentityFile ~/.ssh/github_id_rsa
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_inventory_hostnames:
    - lan

- name: Update the ssh/config with each of the wan node name entries
  tags: ssh
  ansible.builtin.blockinfile:
    create: true
    mode: '0600'
    path: "/home/{{ username }}/.ssh/config"
    block: |
      Host {{ item }}
      Hostname {{ item }}
      User {{ username }}
      IdentityFile ~/.ssh/id_rsa
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_inventory_hostnames:
    - all, !lan

# don't lint-fix this or it will break the task
- name: Update /etc/hosts with each of the lan node name entries
  become: true
  tags: hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['lan'] }}"  # noqa var-spacing
