- name: Update the ssh/config with each of the lan node name entries
  tags: ssh
  become: true
  ansible.builtin.blockinfile:
    create: true
    mode: '0600'
    owner: {{ username }}
    group: {{ username }}
    path: "/home/{{ username }}/.ssh/config"
    block: |
      Host {{ item }}
      Hostname {{ item }}
      ProxyJump home.jasonernst.com
      User {{ username }}
      IdentityFile ~/.ssh/github_id_rsa
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_inventory_hostnames:
    - lan

- name: Add github to ssh/config
  tags: ssh
  become: true
  ansible.builtin.blockinfile:
    create: true
    mode: '0600'
    owner: {{ username }}
    group: {{ username }}
    path: "/home/{{ username }}/.ssh/config"
    block: |
      Host home.jasonernst.com
      Hostname home.jasonernst.com
      User {{ username }}
      IdentityFile ~/.ssh/github_id_rsa
    marker: "# {mark} ANSIBLE MANAGED BLOCK home.jasonernst.com"
