---
- name: Check if vscode apt repo exists
  tags: vscode
  become: true
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/vscode.sources
  register: vscode_repo_exists

- name: Install vscode apt repo
  tags: vscode
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: https://packages.microsoft.com/repos/code
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    suites: [stable]
    components: [main]
    state: present
    enabled: true
  when: not vscode_repo_exists.stat.exists

- name: Install vscode
  become: true
  tags: vscode
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - code

- name: Install jetbrains toolbox
  tags: jetbrains
  ansible.builtin.include_role:
    name: webarchitect609.jet_brains_toolbox
    apply:
      become: true

- name: Ensure group wireshark exists
  become: true
  tags: wireshark
  ansible.builtin.group:
    name: wireshark
    state: present

- name: Add user to group wireshark
  become: true
  tags: wireshark
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wireshark
    append: true

- name: Install wireshark
  tags: wireshark
  become: true
  ansible.builtin.apt:
    pkg:
      - wireshark

- name: Postman
  tags: postman
  become: true
  ansible.builtin.unarchive:
    src: https://dl.pstmn.io/download/latest/linux64
    dest: /opt/
    remote_src: true

- name: Postman app shortcut
  tags: postman
  become: true
  ansible.builtin.copy:
    src: files/postman.desktop
    dest: /usr/share/applications/postman.desktop
    mode: '0664'

- name: Dconf-Editor
  tags: dconf
  become: true
  ansible.builtin.apt:
    pkg:
      - dconf-editor

- name: Virtualbox
  tags: virtualbox
  become: true
  ansible.builtin.apt:
    pkg:
      - virtualbox

- name: Lapce
  ansible.builtin.include_role:
    name: compscidr.lapce
    apply:
      tags: lapce
      become: true
  # https://github.com/ansible/ansible/issues/52063#issuecomment-509142583
  tags: always
