- name: install php development tools
  become: true
  tags: php
  ansible.builtin.apt:
    pkg:
      - composer
      - php-xml
      - php-curl
      - php-mysql
      - php-pdo-sqlite
      - php-pear
      - php-dev
