- name: add php GPG
  tags: php
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
    keyring: /etc/apt/trusted.gpg.d/php.gpg

- name: Add php PPA
  tags: php
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Install php and php dev tools
  tags: php
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.php

- name: install php composer
  become: true
  tags: php
  ansible.builtin.apt:
    pkg:
      - composer

- name: Select default php version
  tags: php
  become: true
  alternatives:
    name: php
    path: "/usr/bin/php{{ php_default_version_debian }}"