---
- name: Common Tasks for all Hosts
  hosts: all
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    - compscidr.uncompress
    - compscidr.gpg
    - common/user
    - common/ssh
    - common/software

- name: Non-GUI Development Software
  hosts: development
  gather_facts: yes
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
    - vars/secrets.yml
  roles:
    - development/shell
    - development/ops
    - development/cpp
    - development/android
    - development/php
    - development/python3
    - development/golang
    - development/node
    - development/ziglang
    - development/ruby
    - development/rust
#    - development/tools
    - role: compscidr.github_cli.github_cli
    - role: compscidr.github_cli.github_cli_extension
      vars:
        github_cli_extension: "dlvhdr/gh-dash"

- name: Development Software for GUIs
  hosts: development_gui
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    - development_gui/ides
    - development_gui/tools
    - development_gui/i3

- name: Services for nas.local
  hosts: nas_local
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
    - vars/secrets.yml
  roles:
    - nas_local/transmission
    - nas_local/home_assistant
    - nas_local/rust_game
    - role: compscidr.media_server.transmission
      vars:
        transmission_folder: /etc/transmission
        transmission_downloads_folder: /volume1/storage/downloads
        transmission_pid: "999"
        transmission_gid: "10"
    - role: compscidr.media_server.plex
      vars:
        plex_dri_devices: true
        plex_bonjour_port: 5354
        plex_tv_folder: /volume1/storage/tv
        plex_movies_folder: /volume1/storage/movies
        plex_claim: claim-haziyvUxG2Fb4uj5-tF1
        plex_pid: "999"
        plex_gid: "10"
    - role: compscidr.media_server.sabnzbd
      vars:
        sabnzbd_pid: "999"
        sabnzbd_gid: "10"
        sabnzbd_download_folder: /volume1/storage/downloads
    - role: compscidr.media_server.sonarr
      vars:
        sonarr_folder: /etc/sonarr
        sonarr_tv_folder: /volume1/storage/tv
        sonarr_tranmissions_downloads_folder: /volume1/storage/downloads
        sonarr_sabnzbd_downoads_folder: /volume1/storage/downloads/complete
        sonarr_pid: "999"
        sonarr_gid: "10"
    - role: compscidr.media_server.radarr
      vars:
        radarr_movies_folder: /volume1/storage/movies
        radarr_transmission_downloads_folder: /volume1/storage/downloads
        radarr_sabnzbd_downoads_folder: /volume1/storage/downloads/complete
        radarr_pid: "999"
        radarr_gid: "10"
    - role: compscidr.media_server.prowlarr
      vars:
        prowlarr_pid: "999"
        prowlarr_gid: "10"
    - role: compscidr.media_server.flaresolverr
      vars:
        flare_port: 8191

- name: Services for home.jasonernst.com
  hosts: home_jasonernst_com
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
    - vars/secrets.yml
  roles:
    - home_jasonernst_com/dyndns
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "hello-java-android"
        github_runner_java: true
        github_runner_java_mount_usb: true
        github_runner_install_docker: false
        github_runner_repo: "compscidr/hello-java-android"
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "hello-kotlin-android"
        github_runner_java: true
        github_runner_install_docker: false
        github_runner_java_mount_usb: true
        github_runner_repo: "compscidr/hello-kotlin-android"
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "icmp"
        github_runner_java: true
        github_runner_java_mount_usb: true
        github_runner_install_docker: false
        github_runner_repo: "compscidr/icmp"
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "grape"
        github_runner_java: true
        github_runner_java_mount_usb: true
        github_runner_install_docker: false
        github_runner_org: true
        github_runner_org_name: "grape-networking"

- name: Services for www.jasonernst.com
  hosts: www_jasonernst_com
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    - web_common/nginx
    - web_common/letsencrypt
    - www_jasonernst_com/goblog

- name: Services for ombi.jasonernst.com
  hosts: ombi_jasonernst_com
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    # enable these when ombi moves to its own server
    # - web_common/nginx
    # - web_common/letsencrypt
    - role: compscidr.media_server.ombi
      vars:
        ombi_virtual_host: "ombi.jasonernst.com"
        ombi_letsencrypt_email: "ernstjason1@gmail.com"
