---
- name: Common Tasks for all Hosts
  hosts: all
  roles:
    - compscidr.uncompress
    - compscidr.gpg
    - common/user
    - common/ssh
    - common/software
    - common/i3

- name: Tasks for LAN Hosts
  hosts: lan
  roles:
    - common/lan

- name: Tasks for WAN hosts
  hosts: all, !lan
  roles:
    - common/wan

- name: Non-GUI Development Software
  hosts: development
  roles:
    - development/shell
    - development/ops
    - development/cpp
    - development/android
    - development/python3
    - development/golang
    - development/node
    - development/ziglang
    - development/ruby
    - development/rust
    - tunnels

- name: Development Software for GUIs
  hosts: development_gui
  roles:
    - development_gui/ides
    - development_gui/tools

- name: Services for home.jasonernst.com
  hosts: home_jasonernst_com
  roles:
    - home_jasonernst_com/plex
    - home_jasonernst_com/transmission
    - home_jasonernst_com/flaresolver
    - home_jasonernst_com/jackett
    - home_jasonernst_com/sonarr
    - home_jasonernst_com/radarr
    - home_jasonernst_com/rust
    - home_jasonernst_com/honeygain
    - gh_actions/ipv6-docker
    - gh_actions/bump-jvm
    - gh_actions/bump-android
    - gh_actions/compscidr

- name: Services for ubuntu-desktop
  hosts: ubuntu-desktop
  roles:
    - gh_actions/ipv6-docker
    - gh_actions/bump-jvm

- name: Services for www.jasonernst.com
  hosts: www_jasonernst_com
  roles:
    - web_common/nginx
    - web_common/letsencrypt
    - www_jasonernst_com/goblog

- name: Services for lp.jasonernst.com
  hosts: lp_jasonernst_com
  roles:
    - lp_jasonernst_com/grafana
    - livepeer/orchestrator
    - lp_jasonernst_com/prometheus

- name: Services for ombi.jasonernst.com
  hosts: ombi_jasonernst_com
  roles:
    # enable these when ombi moves to its own server
    # - web_common/nginx
    # - web_common/letsencrypt
    - ombi_jasonernst_com/ombi

- name: AMD GPU related tasks
  hosts: amd
  roles:
    - lolminer/amd
    - livepeer/transcoder_cpu

- name: Nvidia GPU related tasks
  hosts: nvidia
  roles:
    - lolminer/nvidia
    - livepeer/transcoder_gpu

# this is the only computer that seems to be fast enough to keep up to the network
# tried previously on ubuntu-desktop and ubuntu-server, but no dice.
# disabled because using an external service now
# - name: Ethereum
#   tags: ethereum
#   hosts: ubuntu-desktop-beast
#   roles:
#     - ethereum/fullnode
