---
- name: Common Tasks for all Hosts
  hosts: all
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    - compscidr.uncompress
    - compscidr.gpg
    - common/user
    - common/ssh
    - common/software

- name: Non-GUI Development Software
  hosts: development
  gather_facts: yes
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    - development/shell
    - development/ops
    - development/cpp
    - development/android
    - development/php
    - development/python3
    - development/golang
    - development/node
    - development/ziglang
    - development/ruby
    - development/rust

- name: Development Software for GUIs
  hosts: development_gui
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    - development_gui/ides
    - development_gui/tools
    - development_gui/i3

- name: Services for home.jasonernst.com
  hosts: home_jasonernst_com
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
    - vars/secrets.yml
  roles:
    - home_jasonernst_com/plex
    - home_jasonernst_com/transmission
    - home_jasonernst_com/flaresolver
    - home_jasonernst_com/jackett
    - home_jasonernst_com/sonarr
    - home_jasonernst_com/radarr
    - home_jasonernst_com/rust_game
    - home_jasonernst_com/sabnzbd
    - home_jasonernst_com/prowlarr
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "hello-java-android"
        github_runner_java: true
        github_runner_install_docker: false
        github_runner_repo: "compscidr/hello-java-android"
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "hello-kotlin-android"
        github_runner_java: true
        github_runner_install_docker: false
        github_runner_repo: "compscidr/hello-kotlin-android"
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "grape"
        github_runner_java: true
        github_runner_install_docker: false
        github_runner_org: true
        github_runner_org_name: "grape-networking"

- name: Services for www.jasonernst.com
  hosts: www_jasonernst_com
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    - web_common/nginx
    - web_common/letsencrypt
    - www_jasonernst_com/goblog

- name: Services for ombi.jasonernst.com
  hosts: ombi_jasonernst_com
  vars_files:
    - vars/deb_arch.yml
    - vars/user.yml
  roles:
    # enable these when ombi moves to its own server
    # - web_common/nginx
    # - web_common/letsencrypt
    - ombi_jasonernst_com/ombi