# python dev tools
- name: install python development tools
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-setuptools
      - python-is-python3
