- name: Create Sabnzbd Directories
  tags: sabnzbd
  become: true
  ansible.builtin.file:
    path: /etc/sabnzbd
    state: directory
    mode: '755'
    owner: root
    group: root

# https://nzbusenet.com/en/newznab-providers/
# using althub.co.za
- name: Deploy Sabnzbd
  tags: sabnzbd
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: sabnzbd
    image: linuxserver/sabnzbd:latest
    pull: true
    volumes:
      - "/storage/downloads:/data:rw"
      - "/etc/sabnzbd:/config:rw"
    ports:
      - "8080:8080"
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: 1g
