- name: Create ssh directory if it does not exist
  tags: ssh
  become: true
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ username }}"
    group: "{{ username }}"

# enables the target to ssh into other machines I've deployed via ssh key
# ie: no password required
- name: ssh id_rsa
  tags: ssh
  become: true
  ansible.builtin.copy:
    src: id_rsa
    dest: "/home/{{ username }}/.ssh/id_rsa"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: ssh id_rsa.pub
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: id_rsa.pub
    dest: "/home/{{ username }}/.ssh/id_rsa.pub"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: ssh github_id_rsa
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: github_id_rsa
    dest: "/home/{{ username }}/.ssh/github_id_rsa"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: ssh github_id_rsa.pub
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: github_id_rsa.pub
    dest: "/home/{{ username }}/.ssh/github_id_rsa.pub"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add github to ssh/config
  become: true
  tags: ssh
  ansible.builtin.blockinfile:
    create: true
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
    path: "/home/{{ username }}/.ssh/config"
    block: |
      Host github.com
      Hostname github.com
      User git
      IdentityFile ~/.ssh/github_id_rsa
    marker: "# {mark} ANSIBLE MANAGED BLOCK github"

- name: Add work key
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: bump.pem
    dest: "/home/{{ username }}/.ssh/bump.pem"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
