- name: Create ssh directory if it does not exist
  tags: ssh
  become: true
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ username }}"
    group: "{{ username }}"

# enables the target to ssh into other machines I've deployed via ssh key
# ie: no password required
- name: ssh id_rsa
  tags: ssh
  become: true
  ansible.builtin.copy:
    src: id_rsa
    dest: "/home/{{ username }}/.ssh/id_rsa"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: ssh id_rsa.pub
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: id_rsa.pub
    dest: "/home/{{ username }}/.ssh/id_rsa.pub"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add work key
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: bump.pem
    dest: "/home/{{ username }}/.ssh/bump.pem"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
