- name: Create ssh directory if it does not exist
  tags: ssh
  become: true
  ansible.builtin.file:
    path: /home/jason/.ssh
    state: directory
    mode: '0700'
    owner: jason
    group: jason

# enables the target to ssh into other machines I've deployed via ssh key
# ie: no password required
- name: ssh id_rsa
  tags: ssh
  become: true
  ansible.builtin.copy:
    src: id_rsa
    dest: /home/jason/.ssh/id_rsa
    mode: '0600'
    owner: jason
    group: jason

- name: ssh id_rsa.pub
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: id_rsa.pub
    dest: /home/jason/.ssh/id_rsa.pub
    mode: '0644'
    owner: jason
    group: jason

- name: ssh github_id_rsa
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: github_id_rsa
    dest: /home/jason/.ssh/github_id_rsa
    mode: '0600'
    owner: jason
    group: jason

- name: ssh github_id_rsa.pub
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: github_id_rsa.pub
    dest: /home/jason/.ssh/github_id_rsa.pub
    mode: '0644'
    owner: jason
    group: jason

- name: Add github to ssh/config
  become: true
  tags: ssh
  ansible.builtin.blockinfile:
    create: true
    mode: '0600'
    owner: jason
    group: jason
    path: "/home/jason/.ssh/config"
    block: |
      Host github.com
      Hostname github.com
      User git
      IdentityFile ~/.ssh/github_id_rsa
    marker: "# {mark} ANSIBLE MANAGED BLOCK github"

- name: Add work key
  become: true
  tags: ssh
  ansible.builtin.copy:
    src: jason-test.pem
    dest: /home/jason/.ssh/jason-test.pem
    mode: '0600'
    owner: jason
    group: jason

- name: Add work key to ssh/config
  become: true
  tags: ssh
  ansible.builtin.blockinfile:
    create: true
    mode: '0600'
    owner: jason
    group: jason
    path: "/home/jason/.ssh/config"
    block: |
      Host ec2-54-84-236-202.compute-1.amazonaws.com
      Hostname ec2-54-84-236-202.compute-1.amazonaws.com
      User ubuntu
      IdentityFile ~/.ssh/jason-test.pem
    marker: "# {mark} ANSIBLE MANAGED BLOCK github"
