---
# https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
# https://gist.github.com/roib20/27fde10af195cee1c1f8ac5f68be7e9b
- name: Install 1password apt repo
  tags: 1password
  become: true
  ansible.builtin.deb822_repository:
    name: 1password
    types: [deb]
    uris: https://downloads.1password.com/linux/debian/{{ [ansible_architecture] | map('extract', deb_architecture) | first }}/
    signed_by: https://downloads.1password.com/linux/keys/1password.asc
    suites: [stable]
    components: [main]
    state: present
    enabled: yes

- name: Install 1password cli
  tags: 1password
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - 1password-cli

- name: Ensure GPG directory exists
  tags: gpg
  become_user: "{{ username }}"
  file:
    path: "~/.gpg"
    mode: "0700"
    state: directory

- name: Copy GPG key
  tags: gpg
  become_user: "{{ username }}"
  ansible.builtin.copy:
    content: "{{ lookup('community.general.onepassword', 'GPG Key', field='notesPlain', vault='Infrastructure') }}"
    dest: "~/.gpg/{{ username }}.gpg"
    mode: "0600"
  notify: 
    - Import GPG private key

- name: Configure git preferences
  become_user: "{{ username }}"
  tags: git
  community.general.git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: user.email
      value: "{{ email }}" 
    - name: user.name
      value: "{{ fullname }}"
    - name: init.defaultBranch
      value: main
    - name: user.signingkey
      value: "{{ signingkey }}"

- name: Create docker group
  tags: docker
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  tags: docker
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  notify: Reset ssh connection    

- name: Install various cli tools
  become: true
  tags: cli-tools
  ansible.builtin.apt:
    pkg:
      - btop                    # modern and colorful cli resource monitor
      - byobu                   # text window manager / multiplexer / devops env
      - curl                    # http/https/gopher tool
      - docker.io               # containers
      - fish			# friendly interactive shell
      - fzf			# command line fuzzy finder
      - git			# code repos
      - htop                    # better top (uses mouse for example)
      - lm-sensors              # suggested installed with htop
      - nano			# simple command line editor
      - neofetch                # cli system info
      - nvme-cli                # get temperature / stats on nmves
      - powerline               # prompt and statusline utility
      - screen                  # terminal multiplexer
      - stow			# use this to manage dotfiles
      - tmux                    # terminal multiplexer
      - unzip                   # zip files
      - wget                    # curl alternative
      - xclip                   # cli interface for x selections

- name: Install network tools
  become: true
  tags: network-tools
  ansible.builtin.apt:
    pkg:
      - arp-scan                # for ip <-> mac map search
      - dnsutils                # dig
      - ethtool                 # gets info like link speed
      - iftop                   # network top
      - iptables-persistent	# boot-time loader for netfilter rules
      - iotop                   # disk top
      - nbtscan                 # netbios scanner
      - net-tools               # ifconfig, netstat, arp
      - nmap                    # determine open ports
      - socat                   # sort of like nc but doesn't hang
      - sqlite3                 # good db for integration tests
      - sshfs                   # ssh mounts
      - sshuttle                # forward ssh through tunnel
      - tcpstat		        # network interface statistics reporting tool
      - traceroute              # traceroute
      - fail2ban                # https://help.ubuntu.com/community/Fail2ban
      - whois                   # whois

# https://github.com/Strum355/ansible-dotfiles/blob/master/roles/dotfiles/tasks/main.yaml
- name: Clone dotfile repo
  become_user: "{{ username }}"
  tags: dotfiles
  ansible.builtin.git:
    repo: git@github.com:compscidr/dotfiles.git
    dest: ~/dotfiles

- name: Build directories list
  tags: dotfiles
  find:
    paths: [~/dotfiles/]
    recurse: no
    file_type: directory
  register: files
 
- name: Deploy dotfiles!
  become_user: "{{ username }}"
  tags: dotfiles
  with_items: "{{ files.files }}"
  shell: "stow {{ item.path | basename }}"
  args:
    chdir: ~/dotfiles
