{
 "title": "Orchestrator Overview Papa Bear",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orchestrator",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_versions{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Price/Pxl",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_transcoding_price" }
   ]
  },
  {
   "title": "O Max Sessions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_max_sessions_total{}" }
   ]
  },
  {
   "title": "Orchestrators Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"})",
     "legendFormat": "Current sessions"
    }
   ]
  },
  {
   "title": "Winner",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_winning_tickets_recv" }
   ]
  },
  {
   "title": "Gas Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livepeer_suggested_gas_price{node_type=\"orch\"}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Expected payout (ETH)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(livepeer_ticket_value_recv[1y])))/10^9"
    }
   ]
  },
  {
   "title": "Daily Income (ETH)",
   "type": "stat",
   "description": "Based on data from the previous 24h",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepeer_ticket_value_recv[1d])*60*60*24)/10^9"
    }
   ]
  },
  {
   "title": "Instant/Daily Projected Income in ETH",
   "type": "stat",
   "description": "Based on data from the previous 10 minutes",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepeer_ticket_value_recv[10m])*60*60*24)/10^9"
    }
   ]
  },
  {
   "title": "Minutes (sum)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_source_segment_duration_seconds_sum[100y]))/60",
     "legendFormat": "Minutes  Transcoded  (sum)"
    }
   ]
  },
  {
   "title": "Minutes (count)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_source_segment_duration_seconds_count[100y]))/60",
     "legendFormat": "Minutes Transcoded  (count)"
    }
   ]
  },
  {
   "title": "Mins/Day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_source_segment_duration_seconds_count[1d]))/60",
     "legendFormat": "Minutes Transcoded  (count)"
    }
   ]
  },
  {
   "title": "Mins/Hr",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_source_segment_duration_seconds_count[1h]))/60",
     "legendFormat": "Minutes Transcoded  (count)"
    }
   ]
  },
  {
   "title": "Tickets/Min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_tickets_recv[1m]))"
    }
   ]
  },
  {
   "title": "Tickets/Day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_tickets_recv[1d]))"
    }
   ]
  },
  {
   "title": "Tickets Received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_tickets_recv[100y]))"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_used/memory_total", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"}) / sum(livepeer_max_sessions_total{node_type=\"orch\"}) * 100"
    }
   ]
  },
  {
   "title": "Total minutes of transcoded video",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_source_segment_duration_seconds_sum[100y]))/60",
     "legendFormat": "Minutes  Transcoded  (sum)"
    },
    {
     "expr": "sum(increase(livepeer_source_segment_duration_seconds_count[100y]))/60",
     "legendFormat": "Minutes Transcoded  (count)"
    }
   ]
  },
  {
   "title": "Tickets Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# Tickets" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_tickets_recv[100y]))",
     "legendFormat": "Tickets"
    }
   ]
  },
  {
   "title": "T Max Sessions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_transcoders_capacity" }
   ]
  },
  {
   "title": " Transcoders",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_transcoders_number" }
   ]
  },
  {
   "title": "Sessions by Profiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(livepeer_segment_transcoded_total[1m])/ on() group_left() sum(increase(livepeer_segment_transcoded_total[1m]))) * on() group_left() sum(livepeer_current_sessions_total{node_type=\"orch\"})",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Transcode Times (Average)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Transcode Score (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_score_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_score_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "livepeer_suggested_gas_price{node_type=\"orch\"}",
     "legendFormat": "Gas Price"
    }
   ]
  },
  {
   "title": "Transcode Times (Percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Transcode Score (Percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Download Times (Average)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_download_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_download_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "Download Time"
    }
   ]
  },
  {
   "title": "Download Times (Percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Source Duration (Average)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_source_segment_duration_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_source_segment_duration_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Source Duration (Percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}