{
 "title": "Orchestrator Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Daily Projected Income in ETH",
   "type": "stat",
   "description": "Based on data from the previous 24h",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepeer_ticket_value_recv[1d])*60*60*24)/10^9"
    }
   ]
  },
  {
   "title": "Expected Payout in ETH",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "(sum(livepeer_ticket_value_recv)-(sum(livepeer_value_redeemed) OR on() vector(0)))/10^9"
    }
   ]
  },
  {
   "title": "# Orchestrators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_versions{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Orchestrator Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"}) / sum(livepeer_max_sessions_total{node_type=\"orch\"}) * 100"
    }
   ]
  },
  {
   "title": "# Orchestrators Sessions (Continuous)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "# Orchestrator Sessions (Current)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "# Transcoders",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_transcoders_number" }
   ]
  },
  {
   "title": "Transcode Capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_transcoders_capacity" }
   ]
  },
  {
   "title": "Transcode Score (Average)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_score_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_score_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Transcode Score (Percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Transcode Times (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Transcode Times (Percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Source Duration (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_source_segment_duration_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_source_segment_duration_seconds_count{node_type=\"orch\"}[1m])"
    }
   ]
  },
  {
   "title": "Source Duration (Percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Download Times (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_download_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_download_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Times (Percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}